name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Substitua "main" pela branch que você deseja monitorar

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Configura o Node.js (substitua a versão, se necessário)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.5' # Use a versão compatível com seu projeto

      # Instala as dependências do projeto
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # Constrói o projeto (se necessário)
      - name: Build Project
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          run: npx expo export:web

      # Faz o deploy no Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_APP_ID }}
